version: 0.0.0.{build}
skip_tags: true
configuration: Release
init:
- git config --global core.autocrlf true
install:
- ps: npm install -g markdownlint-cli
before_build:
  - cmd: >-
      markdownlint .