version: 0.0.0.{build}
image: Visual Studio 2017
skip_tags: true
configuration: Release
environment:
  DOCKERHUB_USER:
    secure: nGp95rrlpAUWIkJwvo4zyA==
  DOCKERHUB_PASSWORD:
    secure: UD0D3TPijDTAgTcyPS9sWZoljwroOG0XrAE/Wmog/GM=
init:
- git config --global core.autocrlf true
install:
- ps: npm install -g markdownlint-cli
- ps: docker version
build_script:
  - cmd: >-
      cd %BUILD_DIR%

      dotnet restore
      
      dotnet build
  - ps: ./buildDockerImage.ps1 $env:APPVEYOR_BUILD_VERSION $env:APPVEYOR_REPO_BRANCH $env:DOCKERHUB_USER $env:DOCKERHUB_PASSWORD
test_script:
  - cmd: >-
      dotnet vstest ./test/Contentment.Api.Test/bin/Release/netcoreapp1.1/Contentment.Api.Test.dll ./test/Contentment.Api.IntegrationTest/bin/Release/netcoreapp1.1/Contentment.Api.IntegrationTest.dll /logger:trx;LogFileName=results.trx
after_test:
  - ps: ./uploadTestResults.ps1