version: 0.0.0.{build}
skip_tags: true
configuration: Release
init:
- git config --global core.autocrlf true
build_script:
  - cmd: >-
      cd %BUILD_DIR%

      dotnet restore
      
      dotnet build
test_script:
  - cmd: >-
      dotnet vstest ./test/Contentment.Api.Test/bin/Release/netcoreapp1.1/Contentment.Api.Test.dll ./test/Contentment.Api.IntegrationTest/bin/Release/netcoreapp1.1/Contentment.Api.IntegrationTest.dll /logger:trx;LogFileName=results.trx
after_test:
  - ps: ./uploadTestResults.ps1